'use strict';mix_d("BuffetDisclaimersCards__trustx-pricing-desktop-card:trustx-pricing-desktop-card__RKqgqd38",["exports","tslib","@p/A","@c/metrics","@c/scoped-dom"],function(r,t,F,p,G){function u(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var g=u(F),H=u(G),v={},q=function(a,d,e){void 0===d&&(d="");void 0===e&&(e=1);d=a+d;v.hasOwnProperty(d)||(v[d]=!0,p.count(a,(p.count(a)||0)+e))},K=function(a){q(g["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");
var d=function(b,c){b={$event:{preventDefault:g["default"].$.noop,stopPropagation:g["default"].$.noop},$target:b.getContent().find('[data-a-tab-name="'+c+'"]'),data:{name:"energyEfficiencyTabSet"}};g["default"].trigger("a:declarative:a-tabs:click",b)},e=function(b,c){var f=b&&b.$event,k=b&&b.data||{},I=k.activeTabName,J=k.modalHeight,w=k.name;f&&f.preventDefault&&f.preventDefault();f&&f.stopPropagation&&f.stopPropagation();f=c.get(w);f||(g["default"].on("a:popover:beforeShow:"+w,function(h){h.popover&&
h.popover.getContent&&(h=h.popover.getContent(),h.find(".a-manually-loaded").parent().css("min-height",J),g["default"].loadDescendantImagesManually(h))}),f=c.create(b.$target,k));f.show();d(f,I)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",function(b){g["default"].declarative("card-energy-efficiency-secondary-view","click",function(c){q("Card:EERU:SharedLib:mobile:click",c&&c.data&&c.data.name||"");e(c,b)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",
function(b){g["default"].declarative("card-energy-efficiency-modal","click",function(c){q("Card:EERU:SharedLib:desktop:click",c&&c.data&&c.data.name||"");e(c,b)})})},L=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(d){var e=g["default"].$;e(".energyEfficiencyContainer").each(function(b,c){b=e(c).find(".energyEfficiencyProductFicheLabel").first();c=e(c).find("svg").first();b.parent().outerHeight()>c.outerHeight()&&(b.removeClass("a-size-small"),b.addClass("a-size-micro"),
b.parent().outerHeight()>c.outerHeight()&&b.parent().css("line-height","10px"))})})},M=function(){var a=window.P;K(a);L(a)},x=function(a,d,e,b){void 0===b&&(b=1);p.count(a+"."+d+"."+e,b)},y;(function(a){a.BEFORE_FIRST_OPEN="before first open";a.OPEN="open";a.CLOSE="close"})(y||(y={}));var z;(function(a){a.RIGHT_OUT_OF_SCREEN="-120%";a.INSIDE_SCREEN="0px"})(z||(z={}));var l;(function(a){a.MOBILE="mobile";a.DESKTOP="desktop"})(l||(l={}));var m;(function(a){a.ATF="ATF";a.BTF="BTF";a.PRICING="PRICING"})(m||
(m={}));var A;(function(a){a.SW="SW";a.DIS="DIS";a.CER="CER";a.ENV="ENV";a.GPSR="GPSR"})(A||(A={}));var B;(function(a){a.Sidesheet="Sidesheet";a.BTF="BTF"})(B||(B={}));var C;(function(a){a.FATAL="FATAL";a.ERROR="ERROR";a.WARN="WARN"})(C||(C={}));var D;(function(a){a[a.PSI=0]="PSI";a[a.RSP_MANUFACTURER=1]="RSP_MANUFACTURER";a[a.PD=2]="PD";a[a.RED=3]="RED";a[a.LEGAL_WARNINGS_SW=4]="LEGAL_WARNINGS_SW";a[a.LEGAL_WARNINGS_CER=5]="LEGAL_WARNINGS_CER";a[a.LEGAL_WARNINGS_DIS=6]="LEGAL_WARNINGS_DIS"})(D||
(D={}));var E;(function(a){a[a.RSP=0]="RSP";a[a.MANUFACTURER=1]="MANUFACTURER";a[a.PSI=2]="PSI";a[a.PD=3]="PD";a[a.RED=4]="RED";a[a.SAFETYWARNING=5]="SAFETYWARNING";a[a.CERTIFICATION=6]="CERTIFICATION";a[a.DISCLAIMER=7]="DISCLAIMER"})(E||(E={}));var n;(function(a){a.CLIENT_LOAD="Buffet.Client.Load";a.RED_LOADED_CHARGER_INCLUDED="Buffet.Client.RedChargerIncludedLoaded";a.RED_LOADED_NO_CHARGER_INCLUDED="Buffet.Client.RedNoChargerIncludedLoaded";a.INGRESS_LINK_CLICK="Buffet.Sidesheet.IngressLinkClick";
a.RSP_INGRESS_LINK_CLICK="Buffet.Sidesheet.RspIngressLinkClick";a.PD_INGRESS_LINK_CLICK="Buffet.Sidesheet.PdIngressLinkClick";a.PD_ATF_INGRESS_LINK_LOADED="Buffet.Sidesheet.PdAtfIngressLinkLoaded";a.PD_SIDESHEET_LOADED="Buffet.Sidesheet.PdSidesheetLoaded";a.PD_SIDESHEET_WINDOW_OPEN_CLICK="Buffet.SidesheetContent.PdWindowOpen";a.PSI_INGRESS_LINK_CLICK="Buffet.Sidesheet.PsiIngressLinkClick";a.SAFETY_WARNING_PICTOGRAM_CLICK="Buffet.Sidesheet.SafetyWarningPicClick";a.SAFETY_WARNING_PICTOGRAM_LOADED="Buffet.Sidesheet.SafetyWarninPicLoaded";
a.CERTIFICATION_INGRESS_LINK_CLICK="Buffet.Sidesheet.CertificationIngressLinkClick";a.CERTIFICATION_INGRESS_LINK_LOADED="Buffet.Sidesheet.CertificationIngressLinkLoaded";a.CERTIFICATION_PICTOGRAM_CLICK="Buffet.Sidesheet.CertificationPicClick";a.CERTIFICATION_PICTOGRAM_LOADED="Buffet.Sidesheet.CertificationPicLoaded";a.RED_ICON_CLICK_CHARGER_INCLUDED="Buffet.Sidesheet.RedIconClickChargerIncluded";a.RED_ICON_CLICK_NO_CHARGER_INCLUDED="Buffet.Sidesheet.RedIconClickNoChargerIncluded";a.RED_LINK_CLICK_CHARGER_INCLUDED=
"Buffet.Sidesheet.RedLinkClickChargerIncluded";a.RED_LINK_CLICK_NO_CHARGER_INCLUDED="Buffet.Sidesheet.RedLinkClickNoChargerIncluded";a.DISCLAIMER_PICTOGRAM_CLICK="Buffet.Sidesheet.DisclaimerPicClick";a.DISCLAIMER_PICTOGRAM_LOADED="Buffet.Sidesheet.DisclaimerPicLoaded";a.DISCLAIMER_READ_MORE_INGRESS_LINK_CLICK="Buffet.Sidesheet.DisclaimerReadMoreIngressLinkClick";a.DISCLAIMER_READ_MORE_INGRESS_LINK_LOADED="Buffet.Sidesheet.DisclaimerReadMoreIngressLinkLoaded";a.SIDESHEET_OPENED="Buffet.Sidesheet.Open";
a.SIDESHEET_CLOSED="Buffet.Sidesheet.Close";a.SIDESHEET_DWELL_TIME="Buffet.Sidesheet.DwellTime";a.SIDESHEET_CONTENT_LOADED="Buffet.SdesheetContent.Load";a.SIDESHEET_CONTENT_LOAD_LATENCY="Buffet.SidesheetContent.LoadLatency";a.PSI_PILL_CLICK="Buffet.SidesheetContent.PsiPillClick";a.MANUFACTURER_PILL_CLICK="Buffet.SidesheetContent.ManufacturerPillClick";a.RSP_PILL_CLICK="Buffet.SidesheetContent.RspPillClick";a.PD_PILL_CLICK="Buffet.SidesheetContent.PdPillClick";a.RED_PILL_CLICK="Buffet.SidesheetContent.RedPillClick";
a.PSI_ZOOM_IN_CLICK="Buffet.SidesheetContent.PsiZoomInClick";a.PSI_ZOOM_OUT_CLICK="Buffet.SidesheetContent.PsiZoomOutClick";a.GPSR_EXPANDER_OPEN="Buffet.Sidesheet.GpsrExpanderOpen";a.ENVIORNMENTAL_EXPANDER_OPEN="Buffet.Sidesheet.EnviornmantalExpanderOpen";a.SAFETY_WARNINGS_EXPANDER_OPEN="Buffet.Sidesheet.SafetyWarningsExpanderOpen";a.DISCLAIMERS_EXPANDER_OPEN="Buffet.Sidesheet.DisclaimersExpanderOpen";a.CERTIFICATIONS_EXPANDER_OPEN="Buffet.Sidesheet.CertificationsExpanderOpen";a.EEL_BADGE_IMPRESSION=
"EEL.Badge.Impression";a.EEL_BADGE_CLICK="EEL.Badge.Click";a.PD_BTF_WINDOW_OPEN_CLICK="Buffet.BtfContent.PdWindowOpen";a.MISSING_ASIN_ERROR="Buffet.MissingAsin.Error";a.MISSING_CRUCIAL_ELEMENTS_ERROR="Buffet.MissingCrucialElements.Error";a.MISSING_GPSR_CONTENT_ERROR="Buffet.MissingGpsrContent.Error";a.MISSING_PD_ELEMENTS_ERROR="Buffet.MissingExpectedPdElements.Error";a.SIDESHEET_OPEN_ERROR="Buffet.Sidesheet.Open.Error";a.SIDESHEET_CONTENT_LOAD_ERROR="Buffet.Sidesheet.ContentLoad.Error";a.ALL_AAPI_CALL_FAIL=
"Buffet.AllAapiCall.FAIL";a.RSP_MANUFACTURER_AAPI_CALL_FAIL="Buffet.RspManufacturerAapiCall.FAIL";a.PSI_AAPI_CALL_FAIL="Buffet.PsiAapiCall.FAIL";a.PD_AAPI_CALL_FAIL="Buffet.PdAapiCall.FAIL";a.RED_AAPI_CALL_FAIL="Buffet.RedAapiCall.FAIL";a.LEGAL_WARNINGS_AAPI_FAIL="Buffet.LegalWarningsAapiCall.FAIL"})(n||(n={}));r._operationNames=[];r.card=function(){return t.__awaiter(void 0,void 0,void 0,function(){var a;return t.__generator(this,function(d){if(a=H["default"].cardRoot.querySelector(".energyEfficiencyContainer"))M(),
x(l.DESKTOP,m.PRICING,n.EEL_BADGE_IMPRESSION),a.addEventListener("click",function(){x(l.DESKTOP,m.PRICING,n.EEL_BADGE_CLICK)});return[2]})})}});
