/*
 For license information please see main.js.LICENSE.txt */
(function(v){var p=window.AmazonUIPageJS||window.P,J=p._namespace||p.attributeErrors,q=J?J("PRIVCONAssets@centralized-prompting",""):p;q.guardFatal?q.guardFatal(v)(q,window):q.execute(function(){v(q,window)})})(function(v,p,J){function q(h,p,q){p in h?Object.defineProperty(h,p,{value:q,enumerable:!0,configurable:!0,writable:!0}):h[p]=q;return h}var l="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(h){return typeof h}:function(h){return h&&"function"===typeof Symbol&&h.constructor===
Symbol&&h!==Symbol.prototype?"symbol":typeof h};v.when("3p-promise").register("@amzn/consent-orchestration-client-sdk",function(h){var q;(function(){function v(a){var b;(b=function(a){if(Array.isArray(a))return O(a)}(a))||(b="undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"]?Array.from(a):void 0);if(!(a=b||function(a,b){if(a){if("string"==typeof a)return O(a,b);var d={}.toString.call(a).slice(8,-1);return"Object"===d&&a.constructor&&(d=a.constructor.name),"Map"===d||"Set"===
d?Array.from(a):"Arguments"===d||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(d)?O(a,b):void 0}}(a)))throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");return a}function O(a,b){(null==b||b>a.length)&&(b=a.length);for(var e=0,d=Array(b);e<b;e++)d[e]=a[e];return d}function r(){for(var a=arguments.length,b=Array(a),e=0;e<a;e++)b[e]=arguments[e];return b.filter(function(a){return a}).join(".")}
function x(){for(var a=[],b=arguments.length,e=Array(b),d=0;d<b;d++)e[d]=arguments[d];e.forEach(function(b){Array.isArray(b)?a.push.apply(a,v(b)):a.push(b)});b=a.filter(function(a){return"string"==typeof a&&""!==a.trim()}).map(function(a){return a.replace(/,/g,"-")});return r.apply(void 0,v(b))}function m(a){return m="function"==typeof Symbol&&"symbol"==l(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":l(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&
a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":l(a)},m(a)}function W(a,b){for(var e=0;e<b.length;e++){var d=b[e];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,P(d.key),d)}}function K(a,b,e){return(b=P(b))in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e,a}function P(a){a:if("object"==m(a)&&a){var b=a[Symbol.toPrimitive];if(void 0!==b){a=b.call(a,"string");if("object"!=m(a))break a;throw new TypeError("@@toPrimitive must return a primitive value.");
}a=String(a)}return"symbol"==m(a)?a:a+""}function Q(a,b){(null==b||b>a.length)&&(b=a.length);for(var e=0,d=Array(b);e<b;e++)d[e]=a[e];return d}function J(a){return a>Date.now()-R.promptTimeWindow*aa}function u(a){var b=Date.now();return a>=R.promptsUntilCooldown?b+R.readCooldownDuration*aa:void 0}function w(a){return w="function"==typeof Symbol&&"symbol"==l(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":l(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===
Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":l(a)},w(a)}function H(a,b){var e=Object.keys(a);if(Object.getOwnPropertySymbols){var d=Object.getOwnPropertySymbols(a);b&&(d=d.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));e.push.apply(e,d)}return e}function S(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{};b%2?H(Object(e),!0).forEach(function(b){var d,c=e[b];a:if("object"==w(b)&&b){var ea=b[Symbol.toPrimitive];
if(void 0!==ea){b=ea.call(b,"string");if("object"!=w(b))break a;throw new TypeError("@@toPrimitive must return a primitive value.");}b=String(b)}(d="symbol"==w(b)?b:b+"")in a?Object.defineProperty(a,d,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[d]=c}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(e)):H(Object(e)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(e,b))})}return a}function B(a,b){var e,d=D(a,b),c=(e=
d.prompts,[Date.now()].concat(function(a){if(Array.isArray(a))return Q(a)}(e)||function(a){if("undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"])return Array.from(a)}(e)||function(a,b){if(a){if("string"==typeof a)return Q(a,b);var d={}.toString.call(a).slice(8,-1);return"Object"===d&&a.constructor&&(d=a.constructor.name),"Map"===d||"Set"===d?Array.from(a):"Arguments"===d||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(d)?Q(a,b):void 0}}(e)||function(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}()).filter(J).sort(function(a,b){return b-a}).slice(0,R.promptsUntilCooldown));y(a,{principal:d.principal,prompts:c,defer:u(c.length)},b)}function D(a,b){var e,d,c,t,h=a.id(),f={principal:h,prompts:[]};try{var X=a.get(fa);if(!X)return f;var g=JSON.parse(p.atob(X));return b.emitCount(r(b.appName,k.SERVICE,k.STORE,k.READ)),g.principal===h||(e=h,d=null!==(t=d=g.principal)&&void 0!==t?t:"",(e=null!==(c=e)&&void 0!==c?c:"").length!=d.length&&e.startsWith(d))?S(S({},g),{},{principal:h}):f}catch(ha){return b.emitCount(r(b.appName,
k.SERVICE,k.STORE,k.READ,k.ERROR)),f}}function y(a,b,e){try{var d=p.btoa(JSON.stringify(b));a.set(fa,d);e.emitCount(r(e.appName,k.SERVICE,k.STORE,k.WRITE))}catch(da){e.emitCount(r(e.appName,k.SERVICE,k.STORE,k.WRITE,k.ERROR))}}function M(a){return M="function"==typeof Symbol&&"symbol"==l(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":l(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":
l(a)},M(a)}function N(a){var b="function"==typeof Map?new Map:void 0;return N=function(a){function d(){return function(a,b,d){if(T())return Reflect.construct.apply(null,arguments);var c=[null];c.push.apply(c,b);c=new (a.bind.apply(a,c));return d&&E(c,d.prototype),c}(a,arguments,z(this).constructor)}if(null===a||!function(a){try{return-1!==Function.toString.call(a).indexOf("[native code]")}catch(t){return"function"==typeof a}}(a))return a;if("function"!=typeof a)throw new TypeError("Super expression must either be null or a function");
if(void 0!==b){if(b.has(a))return b.get(a);b.set(a,d)}return d.prototype=Object.create(a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}}),E(d,a)},N(a)}function T(){try{var a=!Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}))}catch(b){}return(T=function(){return!!a})()}function E(a,b){return E=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(a,b){return a.__proto__=b,a},E(a,b)}function z(a){return z=Object.setPrototypeOf?Object.getPrototypeOf.bind():
function(a){return a.__proto__||Object.getPrototypeOf(a)},z(a)}function I(a){return I="function"==typeof Symbol&&"symbol"==l(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":l(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":l(a)},I(a)}function c(){function a(a,b,d){return Object.defineProperty(a,b,{value:d,enumerable:!0,configurable:!0,writable:!0}),a[b]}function b(a,b,c,e){b=Object.create((b&&
b.prototype instanceof d?b:d).prototype);e=new q(e||[]);return v(b,"_invoke",{value:X(a,c,e)}),b}function e(a,b,d){try{return{type:"normal",arg:a.call(b,d)}}catch(ka){return{type:"throw",arg:ka}}}function d(){}function f(){}function t(){}function k(b){["next","throw","return"].forEach(function(d){a(b,d,function(a){return this._invoke(d,a)})})}function g(a,b){function d(c,n,C,Y){c=e(a[c],a,n);if("throw"!==c.type){var F=c.arg;return(c=F.value)&&"object"==I(c)&&A.call(c,"__await")?b.resolve(c.__await).then(function(a){d("next",
a,C,Y)},function(a){d("throw",a,C,Y)}):b.resolve(c).then(function(a){F.value=a;C(F)},function(a){return d("throw",a,C,Y)})}Y(c.arg)}var c;v(this,"_invoke",{value:function(a,n){function C(){return new b(function(b,c){d(a,n,b,c)})}return c=c?c.then(C,C):C()}})}function X(a,b,d){var c=D;return function(n,C){if(c===H)throw Error("Generator is already running");if(c===B){if("throw"===n)throw C;return{value:l,done:!0}}d.method=n;for(d.arg=C;;){if(n=d.delegate)if(n=V(n,d)){if(n===G)continue;return n}if("next"===
d.method)d.sent=d._sent=d.arg;else if("throw"===d.method){if(c===D)throw c=B,d.arg;d.dispatchException(d.arg)}else"return"===d.method&&d.abrupt("return",d.arg);c=H;n=e(a,b,d);if("normal"===n.type){if(c=d.done?B:K,n.arg===G)continue;return{value:n.arg,done:d.done}}"throw"===n.type&&(c=B,d.method="throw",d.arg=n.arg)}}}function V(a,b){var d=b.method,c=a.iterator[d];if(c===l)return b.delegate=null,"throw"===d&&a.iterator.return&&(b.method="return",b.arg=l,V(a,b),"throw"===b.method)||"return"!==d&&(b.method=
"throw",b.arg=new TypeError("The iterator does not provide a '"+d+"' method")),G;d=e(c,a.iterator,b.arg);return"throw"===d.type?(b.method="throw",b.arg=d.arg,b.delegate=null,G):(d=d.arg)?d.done?(b[a.resultName]=d.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=l),b.delegate=null,G):d:(b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,G)}function ha(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);
this.tryEntries.push(b)}function p(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function q(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(ha,this);this.reset(!0)}function r(a){if(a||""===a){var b=a[w];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var d=-1;b=function F(){for(;++d<a.length;)if(A.call(a,d))return F.value=a[d],F.done=!1,F;return F.value=l,F.done=!0,F};return b.next=b}}throw new TypeError(I(a)+" is not iterable");}c=function(){return m};
var l,m={},x=Object.prototype,A=x.hasOwnProperty,v=Object.defineProperty||function(a,b,d){a[b]=d.value},u="function"==typeof Symbol?Symbol:{},w=u.iterator||"@@iterator",E=u.asyncIterator||"@@asyncIterator",z=u.toStringTag||"@@toStringTag";try{a({},"")}catch(n){a=function(a,b,d){return a[b]=d}}m.wrap=b;var D="suspendedStart",K="suspendedYield",H="executing",B="completed",G={};u={};a(u,w,function(){return this});var L=Object.getPrototypeOf;(L=L&&L(L(r([]))))&&L!==x&&A.call(L,w)&&(u=L);var y=t.prototype=
d.prototype=Object.create(u);return f.prototype=t,v(y,"constructor",{value:t,configurable:!0}),v(t,"constructor",{value:f,configurable:!0}),f.displayName=a(t,z,"GeneratorFunction"),m.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===f||"GeneratorFunction"===(a.displayName||a.name))},m.mark=function(b){return Object.setPrototypeOf?Object.setPrototypeOf(b,t):(b.__proto__=t,a(b,z,"GeneratorFunction")),b.prototype=Object.create(y),b},m.awrap=function(a){return{__await:a}},
k(g.prototype),a(g.prototype,E,function(){return this}),m.AsyncIterator=g,m.async=function(a,d,c,e,f){void 0===f&&(f=h);var n=new g(b(a,d,c,e),f);return m.isGeneratorFunction(d)?n:n.next().then(function(a){return a.done?a.value:n.next()})},k(y),a(y,z,"Generator"),a(y,w,function(){return this}),a(y,"toString",function(){return"[object Generator]"}),m.keys=function(a){var b=Object(a),d=[],c;for(c in b)d.push(c);return d.reverse(),function U(){for(;d.length;){var a=d.pop();if(a in b)return U.value=a,
U.done=!1,U}return U.done=!0,U}},m.values=r,q.prototype={constructor:q,reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=l,this.done=!1,this.delegate=null,this.method="next",this.arg=l,this.tryEntries.forEach(p),!a)for(var b in this)"t"===b.charAt(0)&&A.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=l)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,c){return f.type="throw",
f.arg=a,d.next=b,c&&(d.method="next",d.arg=l),!!c}if(this.done)throw a;for(var d=this,c=this.tryEntries.length-1;0<=c;--c){var e=this.tryEntries[c],f=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var t=A.call(e,"catchLoc"),n=A.call(e,"finallyLoc");if(t&&n){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(t){if(this.prev<e.catchLoc)return b(e.catchLoc,!0)}else{if(!n)throw Error("try statement without catch or finally");
if(this.prev<e.finallyLoc)return b(e.finallyLoc)}}}},abrupt:function(a,b){for(var d=this.tryEntries.length-1;0<=d;--d){var c=this.tryEntries[d];if(c.tryLoc<=this.prev&&A.call(c,"finallyLoc")&&this.prev<c.finallyLoc){var e=c;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);d=e?e.completion:{};return d.type=a,d.arg=b,e?(this.method="next",this.next=e.finallyLoc,G):this.complete(d)},complete:function(a,b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===
a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),G},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var d=this.tryEntries[b];if(d.finallyLoc===a)return this.complete(d.completion,d.afterLoc),p(d),G}},catch:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var d=this.tryEntries[b];if(d.tryLoc===a){a=d.completion;if("throw"===a.type){var c=a.arg;p(d)}return c}}throw Error("illegal catch attempt");
},delegateYield:function(a,b,d){return this.delegate={iterator:r(a),resultName:b,nextLoc:d},"next"===this.method&&(this.arg=l),G}},m}function f(a,b,c,d,f,t,k){try{var e=a[t](k),g=e.value}catch(ja){return void c(ja)}e.done?b(g):h.resolve(g).then(d,f)}function g(){var a;return a=c().mark(function da(a,d){var e,f,g=arguments;return c().wrap(function(c){for(;;)switch(c.prev=c.next){case 0:e=2<g.length&&void 0!==g[2]?g[2]:3,f=0;case 2:return c.prev=2,c.next=5,a(d);case 5:return c.abrupt("return",c.sent);
case 8:if(c.prev=8,c.t0=c.catch(2),!(++f>=e)){c.next=13;break}throw c.t0;case 13:return c.next=15,new h(function(a){return setTimeout(a,100)});case 15:if(f<e){c.next=2;break}case 16:case "end":return c.stop()}},da,null,[[2,8]])}),g=function(){var c=this,d=arguments;return new h(function(e,g){function h(a){f(k,e,g,h,t,"next",a)}function t(a){f(k,e,g,h,t,"throw",a)}var k=a.apply(c,d);h(void 0)})},g.apply(this,arguments)}function V(a,b,c,d){var e=b.appName;return function(a,b){return g.apply(this,arguments)}(a,
d,4<arguments.length&&void 0!==arguments[4]?arguments[4]:3).then(function(a){return b.emitCount(r(e,k.SERVICE,x(null==d?void 0:d.metricDimensions),c)),a}).catch(function(a){throw b.emitCount(r(e,k.SERVICE,c,k.ERROR)),new ba("failed to ".concat(c.toLowerCase()," consent for ").concat(e),a);})}function Z(a,b,c,d){var e=b||la,f=c||ma;return d&&ia.adaptiveBackoff.updateConfig(d),{prompt:function(){return function(a,b,d){var c=b.appName;return function(a,b){var d;a=D(a,b);return Date.now()>(null!==(d=
a.defer)&&void 0!==d?d:0)}(d,b)?a().then(function(a){return b.emitCount(r(c,k.SERVICE,x(null==a?void 0:a.metricDimensions),k.PROMPT)),B(d,b),a}).catch(function(a){var e,f=a.status||(null===(e=a.http)||void 0===e?void 0:e.status)||0;if(429!==f&&204!==f)throw b.emitCount(r(c,k.SERVICE,k.PROMPT,k.ERROR)),new ba("failed to prompt for consent for "+c,a);a=D(d,b);y(d,{principal:a.principal,prompts:a.prompts,defer:Date.now()+R.writeCooldownDuration*aa},b);!0}):function(a){return new h(function(b){a.emitCount(r(a.appName,
k.SERVICE,k.PROMPT,k.SKIP));b(null)})}(b)}(a.prompt,e,f)},accept:function(b){return V(a.accept,e,k.ACCEPT,b)},decline:function(b){return V(a.decline,e,k.DECLINE,b)},customize:function(b){return function(a,b,d){var c=b.appName;return a(d).then(function(a){return b.emitCount(r(c,k.SERVICE,x(null==d?void 0:d.metricDimensions),k.CUSTOMIZE)),a}).catch(function(a){throw b.emitCount(r(c,k.SERVICE,k.CUSTOMIZE,k.ERROR)),new ba("failed to customize consent for "+c,a);})}(a.customize,e,b)}}}var A={d:function(a,
b){for(var c in b)A.o(b,c)&&!A.o(a,c)&&Object.defineProperty(a,c,{enumerable:!0,get:b[c]})},o:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},r:function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})}},ca={};A.r(ca);A.d(ca,{initialize:function(){return Z}});var k=function(a){return a.SERVICE="cos",a.PROMPT="prompt",a.ACCEPT="accept",a.DECLINE="decline",a.CUSTOMIZE="customize",
a.STORE="store",a.READ="read",a.WRITE="write",a.ERROR="error",a.SKIP="skip",a}({}),la={appName:"unknown",emitCount:function(a,b){},emitTiming:function(a,b){}},ia={adaptiveBackoff:new (function(){return a=function d(){if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");!0;K(this,"_promptsUntilCooldown",5);K(this,"_promptTimeWindow",10);K(this,"_readCooldownDuration",15);K(this,"_writeCooldownDuration",1440)},b=[{key:"promptsUntilCooldown",get:function(){return this._promptsUntilCooldown},
set:function(a){this._promptsUntilCooldown=a}},{key:"promptTimeWindow",get:function(){return this._promptTimeWindow},set:function(a){this._promptTimeWindow=a}},{key:"readCooldownDuration",get:function(){return this._readCooldownDuration},set:function(a){this._readCooldownDuration=a}},{key:"writeCooldownDuration",get:function(){return this._writeCooldownDuration},set:function(a){this._writeCooldownDuration=a}},{key:"updateConfig",value:function(a){this._promptsUntilCooldown=a.promptsUntilCooldown;
this._promptTimeWindow=a.promptTimeWindow;this._readCooldownDuration=a.readCooldownDuration;this._writeCooldownDuration=a.writeCooldownDuration}},{key:"getConfig",value:function(){return{promptsUntilCooldown:this._promptsUntilCooldown,promptTimeWindow:this._promptTimeWindow,readCooldownDuration:this._readCooldownDuration,writeCooldownDuration:this._writeCooldownDuration}}}],W(a.prototype,b),Object.defineProperty(a,"prototype",{writable:!1}),a;var a,b}())},R=ia.adaptiveBackoff,aa=6E4,fa="sp-cc-pcl",
ma={id:function(){return"unknown"},set:function(a,b){},get:function(a){return""}},ba=function(a){function b(a,c){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var d=b;var e=[a];d=z(d);d=T()?Reflect.construct(d,e||[],z(this).constructor):d.apply(this,e);if(!d||"object"!=M(d)&&"function"!=typeof d){if(void 0!==d)throw new TypeError("Derived constructors may only return object or undefined");if(void 0===this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
d=this}return d.message=a,d.cause=c,d.cause=c,d.name="ConsentOrchestrationError",Object.setPrototypeOf(d,b.prototype),d}return function(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});Object.defineProperty(a,"prototype",{writable:!1});b&&E(a,b)}(b,a),c=b,Object.defineProperty(c,"prototype",{writable:!1}),c;var c}(N(Error));q=ca})();return q});
"use strict";v.when("A","3p-promise","a-util","@amzn/consent-orchestration-client-sdk","ready").execute("centralized-prompting",function(h,l,J,O){var r,x,m=function(){},W={0:(r={name:"cc.banner"},q(r,"NO_VALUE","bannerPopUp"),q(r,"REJECT_ALL",".rejectall.linkbutton"),r),4:{name:"ads.banner"},5:{name:"datashare.banner"},21:{name:"3p.banner"},42:{name:"quebec.banner"}},K=(x={},q(x,"NO_VALUE",".popup"),q(x,"ACCEPT_ALL",".acceptAll"),q(x,"REJECT_ALL",".rejectall"),q(x,"ACCEPT_PARTIAL",".customize"),x),
P=function(c){return new l(function(f,g){h.post("/privacyprefs/retail/v3/banner?pagePath\x3d"+encodeURIComponent(p.location.pathname),{params:{consent:c.payload.url,consentTypes:c.consentTypes},paramsFormat:"json",accepts:"application/json, text/html",contentType:"application/json",timeout:5E3,headers:{"anti-csrftoken-a2z":c.csrfToken},success:function(c){f(c);c&&"string"===typeof c&&-1!==c.indexOf("iframe")&&(c=M("sp-cc-wrapper-pixel",c),N(c),w("revoke.cookie.pixel"))},error:function(c){g(c)}})})},
Q=["x-acb","x-main","x-tacb"],Z=function(){return p.fwcimData&&fwcimData.customerId||Object.keys(J.cookies.getAll()||{}).some(function(c){return Q.some(function(f){return c.startsWith(f)})})?"1":"0"},u=h.capabilities.localStorage?localStorage:{getItem:function(c){return null},setItem:m,removeItem:m},w=p.ue&&"function"===typeof ue.count?function(c){return ue.count(c,1)}:m;w(h.capabilities.localStorage?"sp.cc.localStorage.available":"sp.cc.localStorage.unavailable");var H=p.uet&&p.uex?{start:function(){return uet("bb",
"centralizedConsentBanner",{wb:1})},stop:function(){return uex("ld","centralizedConsentBanner",{wb:1})}}:{start:m,stop:m};H.start();var S=function(){return["[^\x26]*\\/prime\\/offer\\/[^\x26\\/]+\\/prime-deal.*"].some(function(c){return p.location.href.match(c)})},B=O.initialize({prompt:function(){return new l(function(c,f){h.get("/privacyprefs/retail/v3/banner?pagePath\x3d"+encodeURIComponent(p.location.pathname),{success:function(g){g||f(Error("No Data"));g=M("sp-cc-wrapper",g);var l=g.querySelector('input[type\x3d"hidden"][name\x3d"disclosureDecision"]');
g={banner:g,metricDimensions:[l?l.value:"unknown"]};u.getItem("sp-cc-pending")&&(l=g.banner.querySelector("#sp-cc-error"))&&(l.className=(" "+l.className+" ").replace(" aok-hidden "," "));u.removeItem("sp-cc-pending");T(g.banner);I(h.$("#cos-banner"),"NO_VALUE");c(g)},error:function(c){f(c)}})})},accept:function(c){return P(c)},decline:function(c){return P(c)},customize:function(c){return new l(function(f){f(c)})}},{appName:"sp",emitCount:w,emitTiming:m},{id:function(){var c=J.cookies.get("session-id")+
"|"+Z();return p.fwcimData&&fwcimData.customerId?c+"|"+fwcimData.customerId:c},get:function(c){if(!S())return u.getItem(c)},set:function(c,f){S()||u.setItem(c,f)}},{promptsUntilCooldown:5,promptTimeWindow:10,readCooldownDuration:15,writeCooldownDuration:1440}),D=void 0,y=function(){var c=h.$("#cos-banner").outerHeight();"number"!==typeof c||0>=c?document.querySelector("html").style.removeProperty("scroll-padding-bottom"):(c+="px",h.capabilities.mobile?document.querySelector("#a-page").style.marginBottom=
c:document.body.style.paddingBottom=c,document.querySelector("html").style.setProperty("scroll-padding-bottom",c))},M=function(c,f){var g=document.createElement("div");g.id=c;g.innerHTML=f;return g},N=function(c){var f=h.$("#a-page \x3e *:not(script)").first();f.length?f.before(c):document.body.appendChild(c)},T=function(c){N(c);v.when("a-expander").execute(function(c){c.initializeExpanders()})};B.prompt().then(function(){H.stop();D=h.on("orientationchange resize",y);y()}).catch(function(c){H.stop();
throw c;});var E=function(){h.$("#sp-cc-wrapper").remove();u.setItem("sp-cc-pending","1");D&&h.off(D);y()},z=function(c,f){f.$event.preventDefault();var g=c.find('[name\x3d"anti-csrftoken-a2z"]'),h=c.find('[name\x3d"disclosureDecision"]');c=c.find('[name\x3d"consentTypes"]').val();return{payload:f.data,csrfToken:g.val(),metricDimensions:[h.val()],consentTypes:c}};h.declarative("banner-accept-all","click",function(c){var f=h.$("#cos-banner");c=z(f,c);E();B.accept(c).then(function(){u.removeItem("sp-cc-pending");
I(f,"ACCEPT_ALL")})});h.declarative("banner-reject-all","click",function(c){var f=h.$("#cos-banner");c=z(f,c);E();B.decline(c).then(function(){u.removeItem("sp-cc-pending");I(f,"REJECT_ALL")})});h.declarative("banner-customize","click",function(){var c=h.$("#cos-banner"),f=c.find('[name\x3d"disclosureDecision"]');B.customize({metricDimensions:[f.val()]}).then(function(){I(c,"ACCEPT_PARTIAL")})});var I=function(c,f){var g=c.find('[name\x3d"consentTypes"]').val();g&&""!==g.trim()&&0!==g.length&&(g=
g.split(","),h.each(g,function(g){if(W.hasOwnProperty(g)&&p.csa&&"function"===typeof p.csa){var l=csa("Events",{producerId:"cdo-privacy"}),m=W[g],q="NO_VALUE"===f,k=m.hasOwnProperty(f)?m[f]:K[f];m=h.contains(k,".")?m.name+k:k;l("log",{schemaId:"cdo_privacy.anonymia.consent_business_metrics.6",producerId:"cdo-privacy",aaaClientName:"ShoppingPortal",consentType:g,consentValue:m,consentInferredValue:f,consentAdditionalAttribute:"null",clientType:c.find('[name\x3d"clientType"]').val(),privacyCustomerId:c.find('[name\x3d"privacyCustomerId"]').val(),
sessionId:c.find('[name\x3d"sessionId"]').val(),userType:c.find('[name\x3d"userType"]').val(),businessDomain:"1",userId:c.find('[name\x3d"userId"]').val(),tollhouseMarketplaceId:"null",uiEventSource:c.find('input[type\x3d"hidden"][name\x3d"disclosureDecision"]').val(),uiEventActionType:q?"bannerPopUp":"buttonClick"})}}))}})});